silk_road/urls.py
from django.contrib  import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('silk_roads.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

silk_roads/urls.py
"""Defines URL patterns for learning_logs"""
from django.urls import path
from . import views
app_name = 'silk'
urlpatterns = [

    # Home Page
    path('', views.index, name='index'),
    path('story/', views.create_character, name='story'),
    path('game/', views.game_view, name='game'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.custom_logout, name='logout'),
    ]

silk_roads/models.py
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

# Custom manager for Player model
class custom_userManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('The username field must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(username, password, **extra_fields)


class custom_user(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(unique=True, max_length=50)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = custom_userManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username
def get_default_user():
    user, created = custom_user.objects.get_or_create(username='default', defaults={'email': 'default@example.com'})
    return user.id  # Return the ID of the user instead of the user object
class Stats(models.Model):
    user = models.ForeignKey(custom_user, default=get_default_user, on_delete=models.CASCADE)
    happiness = models.IntegerField(default=0)
    age = models.IntegerField(default=0)
    reputation = models.IntegerField(default=0)
    rizz = models.IntegerField(default=0)
    influence = models.IntegerField(default=0)
    skills = models.IntegerField(default=0)
    esteem = models.IntegerField(default=0)
    moral_compass = models.IntegerField(default=50)
    battery = models.IntegerField(default=100)


class Character(models.Model):
    user = models.ForeignKey(custom_user, on_delete=models.CASCADE, null=True, related_name='characters')
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    year = models.IntegerField(default= 2024, help_text=" ")
    gender_choices = [
        ( "Male", "Male"),
        ("Female", "Female")
    ]

    gender = models.CharField(max_length=20, choices=gender_choices)

    ethnicity_choices = [
        ("White", "White"),
        ("Black", "Black"),
        ("European", "European"),
        ("Asian", "Asian"),
        ("Hispanic", "Hispanic"),
        ("Middle Eastern", "Middle Eastern"),
        ("South Asian", "South Asian")
    ]

    ethnicity = models.CharField(max_length=20, choices=ethnicity_choices)
    traits_choices = [
        ('Communicator', 'Communicator'),
        ('Innovator', 'Innovator'),
        ('Motivator', 'Motivator'),
        ('Analyzer', 'Analyzer'),
        ('Networker', 'Networker'),
        ('Mentor', 'Mentor'),
        ('Strategist', 'Strategist'),
        ('Empath', 'Empath'),
        ('Visionary', 'Visionary'),
        ('Activist', 'Activist'),
    ]
    traits = models.CharField(max_length=25, choices=traits_choices)
    background = models.CharField(max_length=250, default= " ")

    TYPE_CHOICES = [
        ('Normal', 'Normal'),
        ('Romance', 'Romance'),
        ('Adventure', 'Adventure'),
        ('Success', 'Success'),
        ('Fame', 'Fame'),
        ('Spiritual', 'Spiritual')

    ]
    personality_choices = [
        ('Introvert', 'Introvert'),
        ('Extrovert', 'Extrovert'),
    ]
    type_story = models.CharField(max_length=25, choices=TYPE_CHOICES)
    personality = models.CharField(max_length=20, choices=personality_choices)

def Character_create(name, age, gender,  background, type_story):
    prompt = (f"{name} a {gender}, they are {age} years old, they're background is: ({background}), "
              f"write a short background story for this character by "
              f"crafting a realistic narrative that sets the tone for his {type_story}-oriented story."
              f" Keep it concise, no more than one paragraph.")
    return prompt

silk_roads/forms.py
from django import forms
from .models import Character

class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = ['name', 'age', 'gender', 'ethnicity', 'traits', 'background', 'type_story', 'personality', 'year']

class GameChoiceForm(forms.Form):
    custom_choice = forms.CharField(
        required=False,
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Enter your custom choice here', 'maxlength': '100'})
    )

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)

silk_roads/views.py
from django.shortcuts import render, redirect
from .forms import CharacterForm, GameChoiceForm
from .models import Character_create, Stats
from .configure import adjust_stats

#logout
from django.contrib.auth import logout


from django.http import HttpResponse
import re
import openai
from openai import OpenAI

import os
from django.contrib.auth import authenticate, login
from .models import custom_user

from dotenv import load_dotenv

# Pinecone, vector database.
from pinecone import Pinecone, ServerlessSpec


pc = Pinecone(api_key='2c4fef42-7136-4fde-a0e0-db97ae1c775e')

messages = []

openai.api_key = "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"
client = OpenAI(api_key=openai.api_key)
model = "gpt-4"



def index(request):
    """The home page for CrossRoads"""
    return render(request, 'silk/index.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')  # Retrieve the password from POST data

        user = custom_user.objects.filter(username=username).first()
        if not user:
            # Create a new user if the user doesn't exist
            # Here, we also set the password for the user
            user = custom_user.objects.create_user(username=username, password=password)
        print("Attempting to authenticate user:", username)

        # Authenticate the user using both username and password
        user = authenticate(request, username=username, password=password)


        if user:
            # Create an Index for the user if authenticated.
            index_name = username

            pc.create_index(
                name=index_name,
                dimension=256,
                metric="cosine",
                spec=ServerlessSpec(
                    cloud='aws',
                    region='us-east-1'
                )
            )

            request.session['username'] = username
            # Create variables to use and update later
            i = 0
            request.session['i'] = i


            print("User authenticated. Logging in and redirecting.")
            login(request, user)
            return redirect('silk:story')  # Redirect to the input/index page after login
        else:
            print("User authentication failed.")
    return render(request, 'silk/index.html')


def custom_logout(request):
    # Retrieve the user's index name from the session
    username = request.session.get('username')
    print(username)
    if username:
        # Delete the index
        pc.delete_index(username)

    # Reset user stats...
    # Example: Resetting session stats
    #if 'stats' in request.session:
        #del request.session['stats']

    # Actual logout
    logout(request)
    #messages.info(request, "You have successfully logged out.")
    return redirect('silk:index')  # Redirect to login page or home page

def create_character(request):
    if request.method == 'POST':
        form = CharacterForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            age = request.POST.get('age')
            ethnicity = request.POST.get('ethnicity')
            traits = request.POST.get('traits')
            background = request.POST.get('background')
            type_story = request.POST.get('type_story')
            personality = request.POST.get('personality')
            gender = request.POST.get('gender')
            year = request.POST.get('year')
            form.save()

            # Save the inputs into the session
            request.session['name'] = name
            request.session['age'] = age
            request.session['ethnicity'] = ethnicity
            request.session['traits'] = traits
            request.session['background'] = background
            request.session['type_story'] = type_story
            request.session['personality'] = personality
            request.session['gender'] = gender
            request.session['year'] = year

            # Make the adjustments based on the inputs the user did
            stats = adjust_stats(ethnicity, personality, traits)
            # Save the character changes
            character = form.save(commit=False)
            character.user = request.user
            character.save()

            # Fetch or create the stats for the character and update them
            character_stats, created = Stats.objects.get_or_create(user=character.user)
            character_stats.moral_compass += stats['moral_compass']
            character_stats.rizz += stats['rizz']
            character_stats.reputation += stats['reputation']
            character_stats.influence += stats['influence']
            character_stats.battery += stats['battery']
            character_stats.skills += stats['skills']
            character_stats.esteem += stats['esteem']
            character_stats.save()

            # name, age, gender, traits, background, type_story, personality
            users_character = Character_create(name, age, gender, background, type_story)

            # Construct the absolute path of the file and read from the file of the character background story example.
            file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'background_example.txt')
            with open(file_path, 'r') as f:
                example = f.read().replace('\n', ' ')

            # Just to create the attitude of the bot and generate a response
            response00 = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": "You are a descriptive real-life story creator. "},
                    {"role": "user",
                     "content": (f"Patricio a male, they are 20 years old, their background is: "
                                 f"(Mexican CS major studying in Bremen and in love with this girl called Emma), "
                                 f"write a short background story for this character by "
                                 f"crafting a realistic narrative that sets the tone for his Romance-oriented story."
                                 f" Keep it concise, no more than one paragraph.")},

                    {"role": "assistant", "content": f"{example}"},
                    {"role": "user", "content": f"{users_character}"}
                ]
            )
            response1 = response00.choices[0].message.content.replace('\n', '<br>')

            # Construct the absolute path of the file and read from the file of the world story example.
            file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'world_example.txt')
            with open(file_path, 'r') as f:
                example1 = f.read().replace('\n', ' ')

            # Just to create the attitude of the bot and generate a response
            response01 = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": f"You are a descriptive world story creator of a {type_story}-oriented story. "},
                    {"role": "user",
                     "content": f"describe the world and setting that the character Patricio would be living and interacting with, this is his background story "
                                f"(Mexican CS major studying in Bremen and in love with this girl called Emma)"
                                f"While saying a explicit location where they live, new persons of interest and specific challenges to overcome "
                                f"catering to his story as a extrovert and empath, so that the user"
                                f" has an idea of how his story could unfold. Make it concise, one/two paragraph long."},

                    {"role": "assistant", "content": f"{example1}"},
                    {"role": "user", "content": f"describe the world and setting that {name} would be living and interacting with, this is his background story ({response1}). "
                                                f"While saying a explicit location where they live, new persons of interest and specific challenges to overcome , so that the user"
                                                f" has an idea of how his story could unfold. Make it concise, one/two paragraph long."}
                ]
            )
            response2 = response01.choices[0].message.content.replace('\n', '<br>')

            response03 = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": f"You summarize and return the core plots, sublots, core people, and core challenges of {name}s story in the shortest and most concise way possible. "},
                    {"role": "user",
                     "content": f"Patricio's story: {example} , Patricio's setting and people of interest: {example1} (response max 150 characters)"},

                    {"role": "assistant", "content": f"Central plot: Make Emma my girlfriend\nSubplots: pass CS exams, learn to live abroad\n"
                                                     f"People of Interest: Emma (girl that I am attracted to), Mark (newly made friend)\n"},
                    {"role": "user",
                     "content": f"{name}'s story: {response1}, {name}'s setting and people of interest: {response2}"},
                ]
            )
            response3 = response03.choices[0].message.content.replace('\n', '<br>')
            # Save the responses to the session
            request.session['character_story'] = response1
            request.session['world_story'] = response2
            request.session['plot_story'] = response3

            # Accessing the index created in the user function
            index_name = request.session.get('username')
            if index_name:
                index = pc.Index(index_name)

silk_roads/templates/silk/base.html
{% load static %}
<html>
<head>
    <style>
        body {
            background-image: url('{% static "silk_road/images/place_holder.jpg" %}');
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
    {% block extra_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'silk_road/css/base_styles.css' %}">
    {% endblock extra_styles %}
</head>
<body>
    <div class="header-container clearfix">
        <div class="left">
            Ramz Co.
        </div>
        <div class="right">
            <a href="{% url 'silk:index' %}">Crossroads</a>
        </div>
        <hr>
    </div>
<!-- Logout Form -->
            <form action="{% url 'silk:logout' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="logout-button">Logout</button>
            </form>
    {% block content %}
    {% endblock content %}
</body>
</html>

silk_roads/templates/silk/game.html
{% extends 'silk/base.html' %}
{% load static %}

{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'silk_road/css/base_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'silk_road/css/game_styles.css' %}">
{% endblock extra_styles %}

{% block content %}
<div class="main-container">

    <div class="left-stats-container">
        <h2>Player Stats</h2>
        <ul>
            <li>Age: </li>
            <li>Happiness: {{ stats.happiness }}</li>
            <li>Reputation: {{ stats.reputation }}</li>
            <li>Rizz: {{ stats.rizz }}</li>
            <li>Influence: {{ stats.influence }}</li>
            <li>Self-Esteem: {{ stats.esteem }}</li>
            <li>Social Skills: {{ stats.skills }}</li>
        </ul>
    </div>

    <div class="story-container">
        <div class="location-header">
        <b>{{ location_info|safe }}</b>
    </div>
    <div class="next-segment">
        {{ next_segment|safe }}
    </div>

        <div class="choices-container">
            {% if choices.0 and choices.1 %}
            <form method="post" action="{% url 'silk:game' %}">
                {% csrf_token %}
                <input type="hidden" name="choice" value="{{ choices.0 }}">
                <input type="submit" class="choice-btn" value="{{ choices.0 }}">
            </form>

            <form method="post" action="{% url 'silk:game' %}">
                {% csrf_token %}
                <input type="hidden" name="choice" value="{{ choices.1 }}">
                <input type="submit" class="choice-btn" value="{{ choices.1 }}">
            </form>
            {% endif %}
        </div>

        <div class="choices-container">
            <form method="post" action="{% url 'silk:game' %}">
                {% csrf_token %}
                <input type="text" name="choice" class="custom-choice-input" placeholder="Type your choice here..." required maxlength="100">
                <input type="submit" class="custom-choice-btn" value="Submit Choice">
            </form>
        </div>
    </div>

        <div class="right-stats-container">
            <h2>Moral Compass & Social Battery</h2>
            <div class="moral-compass">Moral Compass: {{ stats.moral_compass }}</div>
            <div class="social-battery">Social Battery: {{ stats.battery }}%</div>
        </div>

        <div class="right-stats-container">
            <h2>Repercussions</h2>
            <div class="repercussions"> {{ repercussions|safe }}</div>
        </div>

       <div class="right-stats-container">
           <h2>Plot and People of Interest</h2>
           <div class="plot"> {{ plot|safe }}</div>

       </div>

</div>

{% endblock content %}

silk_roads/templates/silk/index.html
{% extends 'silk/base.html' %}
{% load static %}

{% block content %}

<title>Crossroads</title>

<div class="center">
<form method="post" action="{% url 'silk:user_login' %}">
    <input type="text" name="username" placeholder="Username" required>
    <input type="password" name="password" placeholder="Password" required>
    {% csrf_token %}
    {{ login_form.as_p }}
    <button type="submit">Login/Register</button>
</form>
</div>



<style>
  .center {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font: Old Standard
  }
</style>

{% endblock content %}

silk_roads/templates/silk/story.html
{% extends 'silk/base.html' %}
{% load static %}

{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'silk_road/css/base_styles.css' %}">
{% endblock extra_styles %}

{% block content %}
<div class="header-container story-header clearfix">
    <h1 class="left">Create Character</h1>
    {% if response1 and response2 %}
        <div class="next-button right">
            <a href="{% url 'silk:game' %}">Next</a>
        </div>
    {% endif %}
</div>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if not response2 %}
    <button type="submit">Create</button>
    {% endif %}
</form>

<!-- Styles for the boxes and their content -->
<style>
    .story-header h1 {
        margin: 0;
        padding: 0;
    }

    .next-button a {
        background-color: #ddd;
        padding: 5px 15px;
        border-radius: 5px;
        text-decoration: none;
        color: #333;
        font-family: 'Old Standard';
    }

    .next-button a:hover {
        background-color: #bbb;
    }

    .response-box {
        border: 1px solid #ccc;
        padding: 20px;
        margin: 20px;
        flex: 1;
        max-width: 45%;
    }

    .title {
        font-weight: bold;
        font-size: 1.5em;
        margin-bottom: 20px;
    }

    .separator-line {
        width: 2%;
        border-left: 1px solid #ccc;
        height: 100%;
        margin: 20px 1%;
    }

    .container {
        display: flex;
        justify-content: space-between;
        margin: 0 auto;
    }
</style>

{% if response1 and response2 %}
<div class="container">
    <div class="response-box">
        <div class="title">Backstory</div>
        {{ response1|safe }}
    </div>

    <div class="separator-line"></div>

    <div class="response-box">
        <div class="title">Location</div>
        {{ response2|safe }}
    </div>
</div>
{% endif %}

{% endblock %}